### ISSUE TITLE
OSError: [Errno 22] Invalid argument 

### ISSUE THREAD

**Issue by projects4rd** [aschmelyun/docker-compose-laravel#91]
Hi Andrew,

First thank you for your great youtube content. Love the way you teach.

I however encountered a problem after downloading and using your docker setup. When I run `docker-compose up -d --build`
all is pulled from DockerHub and I was able to install Laravel following your instructions without any problem. 

The problem begins when I run `docker-compose down` and then `docker-compose up -d --build` again. This does not work anymore giving the following error:

```
Building php
Traceback (most recent call last):
  File "site-packages\docker\utils\build.py", line 96, in create_archive
OSError: [Errno 22] Invalid argument: '\\\\?\\D:\\code\\docker-compose-laravel\\src\\vendor\\bin\\carbon'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 126, in perform_command
  File "compose\cli\main.py", line 1070, in up
  File "compose\cli\main.py", line 1066, in up
  File "compose\project.py", line 615, in up
  File "compose\service.py", line 346, in ensure_image_exists
  File "compose\service.py", line 1125, in build
  File "site-packages\docker\api\build.py", line 160, in build
  File "site-packages\docker\utils\build.py", line 31, in tar
  File "site-packages\docker\utils\build.py", line 100, in create_archive
OSError: Can not read file in context: \\?\D:\code\docker-compose-laravel\src\vendor\bin\carbon
[10928] Failed to execute script docker-compose
```

I do not know how to remedy this and cannot find a solution on the internet.
I am running the latest Docker Desktop on Windows 10.

Thanks,

Rob

**Comment by achubb** [comment]
I also hit this issue on Windows 10 with the same package.

I created a .dockerignore file and added in `src/vendor/`, seemed to solve it for me. Looks to be something path related in Windows. Not sure exactly, but ignoring the vendor directory should prevent this error.
